ARG REV=latest
FROM mbgl/${REV}:linux

# --------------------------------------------------------------------------------------------------
# Set environment variables

ENV CC="gcc-5" \
    CXX="g++-5"
