ARG REV=latest
FROM mbgl/ci:${REV}-linux

# --------------------------------------------------------------------------------------------------
# Set environment variables

ENV CC="gcc-5" \
    CXX="g++-5"
